export const MenuItemTypes = {
    SELECTED_MENU_ITEM_DATA : "SELECTED_MENU_ITEM_DATA",
    MENU_ITEM_DETAIL_LIST : "MENU_ITEM_DETAIL_LIST",
    SELECTED_ITEM_SIZE : "SELECTED_ITEM_SIZE",    
    REMOVE_SELECTED_ITEM : "REMOVE_SELECTED_ITEM", 
    REMOVE_MENU_ITEM_FAVORITE : "REMOVE_MENU_ITEM_FAVORITE",
    ADD_FAVORITE : "ADD_FAVORITE",
    DELETE_FAVORITE : "DELETE_FAVORITE",      
    ADD_ITEM_TO_CART : "ADD_ITEM_TO_CART",
    SELECTED_ITEM_QUANTITY : "SELECTED_ITEM_QUANTITY",
    UPDATE_ITEM_OPTION_CART : "UPDATE_ITEM_OPTION_CART",
    REMOVE_SELECTED_MENU_ITEM_DATA:"REMOVE_SELECTED_MENU_ITEM_DATA",
    RESET_MENU_ITEM:"RESET_MENU_ITEM"
}