export const RestaurantsTypes = {
    GET_RESTAURANTS_DATA : "GET_RESTAURANTS_DATA",
    RESTAURANT_DETAIL : "RESTAURANT_DETAIL",
    LEFT_MENU_TOGGLE : "LEFT_MENU_TOGGLE",
    RESTAURANT_LOCATION_LIST : "RESTAURANT_LOCATION_LIST",
    RESTAURANT_TIMING : "RESTAURANT_TIMING",
    UPDATE_RESTAURANT_DETAIL : "UPDATE_RESTAURANT_DETAIL",
}