export const OrderTypes = {
    CHECK_ORDER_TIME : "CHECK_ORDER_TIME",
    GET_ORDER_TIME : "GET_ORDER_TIME",
    IS_ASAP_TYPE : "IS_ASAP_TYPE",
    EMPTY_ORDER : "EMPTY_ORDER",
    SET_ORDER_ID : "SET_ORDER_ID",
    IS_REDIRECT_TO_CHECKOUT:"IS_REDIRECT_TO_CHECKOUT",
    EMPTY_ORDER_TIME : "EMPTY_ORDER_TIME",
    ADD_CALCULATED_ORDER_TOTAL : "ADD_CALCULATED_ORDER_TOTAL",
}