export const MainTypes = {
    GET_MENU_CATEGORY_DATA : "GET_MENU_CATEGORY_DATA",    
    GET_PROMOTION_CATEGORY_DATA : "GET_PROMOTION_CATEGORY_DATA",
    GET_SELECTED_RESTAURANTTIME : "GET_SELECTED_RESTAURANTTIME",
    UPDATE_MENU_CATEGORY_DATA : "UPDATE_MENU_CATEGORY_DATA",   
    UPDATE_PROMOTION_CATEGORY_DATA : "UPDATE_PROMOTION_CATEGORY_DATA",
}