export const DeliveryAddressTypes={
    ADD_ADDRESS : "ADD_ADDRESS",
    GET_ADDRESS : "GET_ADDRESS",
    DELETE_ADDRESS : "DELETE_ADDRESS",
    UPDATE_ADDRESS_CHECK :"UPDATE_ADDRESS_CHECK",
    REGISTER_ADDRESS :"REGISTER_ADDRESS",
    UPDATE_ADDRESS_ID :"UPDATE_ADDRESS_ID", 
    ADD_TEMP_DELIVERY_ADDRESS:"ADD_TEMP_DELIVERY_ADDRESS",
    DELETE_TEMP_DELIVERY_ADDRESS :"DELETE_TEMP_DELIVERY_ADDRESS",
    RESET_DELIVERY_ADDRESS:"DELIVERY_ADDRESS"
};

