export const RegisterTypes={
    REGISTER_USER_BEGIN : "REGISTER_USER_BEGIN",
    REGISTER_USER_SUCCESS : "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE : "REGISTER_USER_FAILURE",
    RESET_REGISTER:"RESET_REGISTER"
};
