export const SelectedDeliveryTypes = {
    SAVE_CHOOSE_TIME :"SAVE_CHOOSE_TIME",
    SET_PICKUP_OR_DELIVERY :"SET_PICKUP_OR_DELIVERY",
    SELECTED_DELIVERY_ADDRESS: "SELECTED_DELIVERY_ADDRESS",
    CLEAR_DELIVERY_ADDRESS: "CLEAR_DELIVERY_ADDRESS",
    RESET_SELECTDELIVERY:"RESET_SELECTDELIVERY"
}